Hooks for status code and on unauthorized
ynohat/akamai-g2o pull request #1
Opened 2017-02-01 21:27 UTC by cross311

We have a requirement to log out when the request is unauthorized, even when we do not have it in strict mode.

Currently `401` means something special to our app, so we configured ours to return `407` invalid proxy.

I am up for any suggestions on naming and implementation.

2017-02-01 23:13 UTC, ynohat requested changes
Thanks a lot for your PR. I think you've touched on a flaw in the design of the interface (the strict parameter is dodgy).

I agree with your idea of a hook, please see the contents of the review for an idea to adjust the implementation.

2017-02-01 23:13 UTC, ynohat commented on lib/middleware.js
> +
Thanks for the following defaults, much cleaner.

2017-02-01 23:13 UTC, ynohat commented on README.md
> +If provided, the function will be called after all checks have been completed and found to be unauthenticated.
This should read "if provided, and if the strict option is true" in keeping with your changes.

To be honest, the `strict` parameter was introduced precisely for this: set it to false and write your own middleware to handle the error however you choose.

A better idea might be to remove the `strict` parameter entirely (and bump the major version to 2 :p), and delegate `res.end()` to your `onUnauthenticated` hook. The default implementation would end the request with ~401~ 403, but it would be trivial to implement a different behaviour, e.g.:

```javascript
var strict = true;
var g2oOpts = {
  // ... other opts
  onUnauthenticated: (req, res, next)  => {
    // ... logging
    if (strict) {
      res.status(407).end("Bad Ghost!");
    } else {
      next();
    }
  }
```

I think I like this better, because it strikes the right balance between keeping the hook "middleware-ish" and still providing a sensible builtin default behaviour (fail with 401). Thoughts?

2017-02-02 21:52 UTC, cross311 commented on README.md
> +If provided, the function will be called after all checks have been completed and found to be unauthenticated.
I like this idea.  I did not like how the two were related but not.  This is an easier to understand solution.

2017-02-02 22:08 UTC, ynohat commented on README.md
> +If provided, the function will be called after all checks have been completed and found to be unauthenticated.
Great! And I realise now that I've been sending 401 back when I should really be sending 403. I'll fix that after this PR is merged.

2017-02-02 22:31 UTC, cross311 commented
@ynohat I have made changes, based on what I think you wanted.  Also added a change log so people can see what changed.

I left strict in docs giving an obvious mark it was removed.

2017-02-02 23:46 UTC, merged

2017-02-02 23:47 UTC, ynohat commented
@cross311 I'll shoot you an email when 2.0 is on npm;

Thanks a lot for this.